---
- name: Install a list of packages
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - libffi-dev
    - libssl-dev
    - python3
    - python3-pip
- name: Remove python-configparser package
  apt:
    name: python-configparser
    state: absent
- name: get docker convenience script
  shell: curl -fsSL https://get.docker.com -o get-docker.sh
  args:
    creates: /home/ubuntu/get-docker.sh
- name: install docker
  shell: sh /home/ubuntu/get-docker.sh
  args:
    creates: /usr/bin/docker
- name: make ubuntu user execute docker commands
  shell: usermod -aG docker ubuntu

- name: Ensure that docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes